<!-- # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. -->
<!-- # Generated by scripts/import-svg-icons.js -->
<template>
  <svg-icon
    :data="svg[$props.name]"
    :width="$props.width"
    :height="$props.height"
    original
  ></svg-icon>
</template>
<script>
import { defineComponent } from 'vue'
import duck from '@/assets/icons/ui/duck.svg'
import joker from '@/assets/icons/ui/joker.svg'
import lv0 from '@/assets/icons/ui/lv0.svg'
import lv1 from '@/assets/icons/ui/lv1.svg'
import lv2 from '@/assets/icons/ui/lv2.svg'
import lv3 from '@/assets/icons/ui/lv3.svg'
import lv4 from '@/assets/icons/ui/lv4.svg'
import lv5 from '@/assets/icons/ui/lv5.svg'
import lv6 from '@/assets/icons/ui/lv6.svg'
import sakura from '@/assets/icons/ui/sakura.svg'
import sofa from '@/assets/icons/ui/sofa.svg'
import spring from '@/assets/icons/ui/spring.svg'

export default defineComponent({
  props: {
    name: { type: String },
    width: { type: String, default: '100%' },
    height: { type: String, default: '100%' },
  },
  setup() {
    const svg = {
      duck: duck,
      joker: joker,
      lv0: lv0,
      lv1: lv1,
      lv2: lv2,
      lv3: lv3,
      lv4: lv4,
      lv5: lv5,
      lv6: lv6,
      sakura: sakura,
      sofa: sofa,
      spring: spring,
    }
    return {
      svg,
    }
  },
})
</script>
