// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Generated by scripts/options-export/dump-options.ts
export interface SakuraOptions {
  'basic.site.title': any
  'basic.site.logo': any
  'homepage.slogan': any
  'homepage.quote': any
  'homepage.signature': any
  'homepage.cover.image': any
  'social.github': any
  'social.gitlab': any
  'social.twitter': any
  'social.weibo': any
  'social.facebook': any
  'social.stackoverflow': any
  'thirdParty.reCaptcha.enable': any
  'thirdParty.reCaptcha.version': any
  'thirdParty.reCaptcha.siteKey': any
  'thirdParty.reCaptcha.secretKey': any
  'other.hello': any
  'demo.string': any
  'demo.longString': any
  'demo.switcher': any
  'demo.choose': any
  'demo.selection': any
  'demo.mediaPicker': any
}
